### PR TITLE
Some fixes

### LINKED ISSUE #4: /usr/bin/env: ‘node\r’: No such file or directory
the `\r\n` line ends break the binary on linux
this only appears when i install with yarn (yarn@1)

```sh
cd $(mktemp -d)
yarn init -y
yarn add ts-to-jsdoc
jq -r .version node_modules/ts-to-jsdoc/package.json 
# 1.1.2
npx ts-to-jsdoc
# /usr/bin/env: ‘node\r’: No such file or directory
# /usr/bin/env: use -[v]S to pass options in shebang lines
hexdump -C node_modules/.bin/ts-to-jsdoc | head -n2
# 00000000  23 21 2f 75 73 72 2f 62  69 6e 2f 65 6e 76 20 6e  |#!/usr/bin/env n|
# 00000010  6f 64 65 0d 0a 22 75 73  65 20 73 74 72 69 63 74  |ode.."use strict|
printf '\r\n' | hexdump -C
# 00000000  0d 0a                                             |..|
# 00000002
wget https://registry.yarnpkg.com/ts-to-jsdoc/-/ts-to-jsdoc-1.1.2.tgz
tar xf ts-to-jsdoc-1.1.2.tgz
hexdump -C package/bin/ts-to-jsdoc | head -n2
# 00000000  23 21 2f 75 73 72 2f 62  69 6e 2f 65 6e 76 20 6e  |#!/usr/bin/env n|
# 00000010  6f 64 65 0d 0a 22 75 73  65 20 73 74 72 69 63 74  |ode.."use strict|
wget https://registry.npmjs.com/ts-to-jsdoc/-/ts-to-jsdoc-1.1.2.tgz
# same
```

workaround

```
node node_modules/.bin/ts-to-jsdoc
```

the `\r` is not in the source code,
so i guess you edited the `bin/ts-to-jsdoc` file manually before publish
fix: add a build script `tsc --build` which runs on `npm publish`

next error

```sh
npx ts-to-jsdoc -o src-jsdoc src/

# Error: Cannot find module '../index'
```

fix

```sh
sed -i 's,"../index","ts-to-jsdoc/index.js",' node_modules/.bin/ts-to-jsdoc
```

next error

```sh
npx ts-to-jsdoc -o src-jsdoc/ src/

# [ERROR] Output directory /tmp/src-jsdoc does not exist.
```

workaround

```
mkdir src-jsdoc
```

### LINKED ISSUE #5: param is too verbose. should use only simple param names
input

```ts
function f({
  a,
  b,
}: {
  a: string,
  b: number,
}, arg2: string) {
  return a + arg2
}
```

actual

```js
/**
 * @param {{
 *   a: string,
 *   b: number,
 * }} {
 *   a,
 *   b,
 * }
 * @param {string} arg2
 * @returns {string}
 */
function f({ a, b, }, arg2) {
    return a + arg2;
}
```

expected: remove the `{ a, b }`

```js
/**
 * @param {{
 *   a: string,
 *   b: number,
 * }}
 * @param {string} arg2
 * @returns {string}
 */
function f({ a, b, }, arg2) {
    return a + arg2;
}
```

javascript has only positional arguments (compared to python's kwargs)
so it's safe to skip the variable name if its too complex

### PR DESCRIPTION
**Pull request by milahu**
fix #5 
maybe fix #4

### CODE REVIEW

**Comment by futurGH** [comment]
Thanks for the contribution! This looks great for the most part; frankly more effort than I put into what was really just a throwaway script I decided to publish.

File: index.ts [hunk 1]
```diff
@@ -78,23 +81,29 @@ function generateParameterDocumentation(functionNode: FunctionLikeDeclaration):
...
 			});
 		}
 	}
 }
 
-/** Generate @returns documentation from function return type */
+/**
+ * Generate @returns documentation from function return type
+ * the new jsDoc is stored in functionNode
+*/
```
Comment (futurGH) [inline index.ts]:
```suggestion
/** Generate @returns documentation from function return type and attach it to functionNode */
```
Good idea to include this info, though it doesn't need to be on a separate line. Same goes for the other instances where this line was added.

File: index.ts [hunk 2]
```diff
@@ -302,15 +320,26 @@ function transpile(
...
 		sourceFile.getFunctions().forEach(generateFunctionDocumentation);
 
-		const result = project.emitToMemory()?.getFiles()?.[0]?.text;
+		let result = project.emitToMemory()?.getFiles()?.[0]?.text;
 		if (result) {
+			if (!result.startsWith(protectCommentsHeader)) {
+				throw Error(
+					`internal error: protectCommentsHeader is missing in output\n\n` +
+					`protectCommentsHeader: ${JSON.stringify(protectCommentsHeader)}\n` +
+					`result: ${JSON.stringify(result.slice(protectCommentsHeader.length + 100) + " ...")}`
```
Comment (futurGH) [inline index.ts]:
```suggestion
					`Internal error: generated header is missing in output\n\n` +
					`protectCommentsHeader: ${JSON.stringify(protectCommentsHeader)}\n` +
					`result: ${JSON.stringify(result.slice(protectCommentsHeader.length + 100) + " ...")}`
```
Likely less confusing to avoid mentioning the variable name in the error message; why does the header need to be `JSON.stringif`[ied]?

File: index.ts [hunk 3]
```diff
@@ -302,15 +320,26 @@ function transpile(
...
+				)
+			}
+			result = result.slice(protectCommentsHeader.length);
```
Comment (futurGH) [inline index.ts:327]: Is there any reason a string.replace wouldn't work here or be potentially less error-prone?

File: index.ts (hunk 2 above)
Comment (milahu) [reply index.ts]: helpful for debugging, when ts-morph/typescript returns an unexpected value
we want to remove exactly what we added

File: index.ts (hunk 3 above)
Comment (milahu) [reply index.ts:327]: string.replace would be needed if typescript would transform the source string
but here we have asserted that its exactly the same string, so we can just cut by length

File: index.ts (hunk 1 above)
Comment (milahu) [reply index.ts]: oh come on .... ^^

**Comment by milahu** [comment]
> just a throwaway script

yeah ... i wanted to throw this at `patch-package` to remove typescript, but keep types in jsdoc comments

but ultimately, the typescript syntax is better, and compiling is fast enough
(also there is deno to run typescript directly)
(also javascript has no nested block comments, and [triple slash jsdoc comments](https://github.com/microsoft/TypeScript/pull/39930) are not implemented)

i also tried to patch ts-morph to make every TypedNode also a JSDocableNode
but i had no success in monkey-patching the import
probably we would need to patch the ts-morph source, as in https://github.com/dsherret/ts-morph/issues/193

File: index.ts (hunk 2 above)
Comment (futurGH) [reply index.ts]: Sorry, I was referring to `JSON.stringify(protectCommentsHeader)`. Since it's a defined constant variable where we know its content, in what scenario would the `JSON.stringify` call produce a more desirable output than just including the variable without the wrapping function call?

**Comment by futurGH** [comment]
Ah, I wasn't sure if the lack of `JSDocableNode` was intentional on `ts-morph`'s end when I wrote this. I don't foresee much change to this codebase, so I think we're fine with the custom intersection type and perhaps less-than-ideal assertion given that it seems to work well enough. I might take another look at that if the assumption that every node `ts-to-jsdoc` touches is JSDocable starts causing errors, though.

File: index.ts (hunk 2 above)
Comment (milahu) [reply index.ts]: exact diff

**Comment by milahu** [comment]
> lack of `JSDocableNode` was intentional on `ts-morph`'s end

they implement a narrow spec of jsdoc (blocks: functions and classes)
but vscode can also parse jsdoc for statements

```js
/** @type string */
let declaredVar;

declaredVar = 1;
```

```json
// vscode settings.json
{
  "js/ts.implicitProjectConfig.checkJs": true
}
```

**Comment by milahu** [comment]
can we haz merge?

im not planning to do much more on this, as i dont need ts-to-jsdoc for now

**Comment by futurGH** [comment]
Sorry! I haven't had the time to take a look at this PR on my own machine yet — I think we can do without the tests for now considering that there still appears to be some work to be done there and I don't have the time to work on tests much myself. I'll try and merge in the rest soon.

**Comment by milahu** [comment]
thanks! : )
